// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATCiVkg96ZjW2waUGn_h8EqXW5DHxp-Oc',
    appId: '1:33434653243:web:c5a44a18aa4c438638821e',
    messagingSenderId: '33434653243',
    projectId: 'agritrace-rw',
    authDomain: 'agritrace-rw.firebaseapp.com',
    storageBucket: 'agritrace-rw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATCiVkg96ZjW2waUGn_h8EqXW5DHxp-Oc',
    appId: '1:33434653243:android:c5a44a18aa4c438638821e',
    messagingSenderId: '33434653243',
    projectId: 'agritrace-rw',
    storageBucket: 'agritrace-rw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATCiVkg96ZjW2waUGn_h8EqXW5DHxp-Oc',
    appId: '1:33434653243:ios:c5a44a18aa4c438638821e',
    messagingSenderId: '33434653243',
    projectId: 'agritrace-rw',
    storageBucket: 'agritrace-rw.firebasestorage.app',
    iosClientId: '33434653243-placeholder.apps.googleusercontent.com',
    iosBundleId: 'rw.agritrace.app',
  );
}
